import { useEffect, useMemo, useState } from 'react'
import { BadgeDollarSign, Calculator, Check, Copy, Factory, Fuel, Gauge, RotateCcw, Search, Truck, Users, WalletCards } from 'lucide-react'
import toast from 'react-hot-toast'
import { Link } from 'react-router-dom'
import {
  OFFICIAL_VALUES, calculateEfficiency, calculateFleetCost, calculateFuel, calculateLiquidation,
  calculateMonthlyIsr, calculateOperatorCost, calculateSettlement, calculateTripCost, calculateTripProfit,
} from '../features/calculators/calculations.js'
import Reveal from '../components/ui/Reveal.jsx'

const currency = new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2})
const number = new Intl.NumberFormat('es-MX',{maximumFractionDigits:2})
const today = new Date().toISOString().slice(0,10)

const tools = [
  { id:'isr', category:'Laboral y fiscal', title:'ISR mensual 2026', icon:BadgeDollarSign, summary:'Retención estimada antes de subsidio al empleo.', calculate:calculateMonthlyIsr, fields:[field('taxableIncome','Ingreso gravable mensual','number',30000,'MXN')], note:'Usa la tarifa mensual 2026 del artículo 96. No incluye subsidio al empleo, IMSS, INFONAVIT, deducciones ni ajustes del patrón.', sources:['sat'] },
  { id:'finiquito', category:'Laboral y fiscal', title:'Finiquito', icon:WalletCards, summary:'Prestaciones proporcionales al terminar una relación laboral.', calculate:calculateSettlement, fields:[field('monthlySalary','Salario mensual','number',15000,'MXN'),field('startDate','Fecha de ingreso','date','2024-01-15'),field('endDate','Fecha de salida','date',today),field('pendingSalary','Salario pendiente','number',0,'MXN'),field('vacationDaysTaken','Vacaciones disfrutadas en el periodo','number',0,'días'),field('aguinaldoDays','Días de aguinaldo pactados','number',15,'días'),field('vacationPremium','Prima vacacional','number',25,'%')], note:'Estimación bruta. No descuenta ISR ni incluye prestaciones contractuales no capturadas, comisiones, salarios caídos o adeudos.', sources:['lft'] },
  { id:'liquidacion', category:'Laboral y fiscal', title:'Liquidación', icon:Users, summary:'Escenario orientativo de indemnización por separación.', calculate:calculateLiquidation, fields:[field('integratedDailySalary','Salario diario integrado','number',650,'MXN/día'),field('yearsWorked','Años trabajados','number',3,'años'),select('salaryZone','Zona salarial',[['general','General (Manzanillo)'],['border','Frontera norte']],'general'),check('includeTwentyDays','Incluir 20 días por año',false),field('accruedBenefits','Finiquito y prestaciones pendientes','number',0,'MXN')], note:'Los 20 días por año no proceden automáticamente en todo despido. Revisa el supuesto de los artículos 48–50 con una persona especialista laboral.', sources:['lft','conasami'] },
  { id:'km', category:'Viaje', title:'Costo por kilómetro', icon:Calculator, summary:'Costo completo y costo unitario de un viaje.', calculate:calculateTripCost, fields:[field('distance','Distancia total','number',600,'km'),field('efficiency','Rendimiento','number',2.2,'km/L'),field('dieselPrice','Precio real del diésel','number',26.5,'MXN/L'),field('idleLiters','Consumo en maniobras/ralentí','number',10,'L'),field('tolls','Casetas','number',2500,'MXN'),field('operatorCost','Operador y viáticos','number',1800,'MXN'),field('maintenancePerKm','Mantenimiento por km','number',1.8,'MXN/km'),field('tiresPerKm','Llantas por km','number',0.9,'MXN/km'),field('fixedAllocation','Costos fijos asignados','number',1200,'MXN'),field('other','Otros costos','number',0,'MXN')], note:'Captura distancia de ida, regreso y recorridos locales. Las tarifas de casetas y el precio de combustible deben provenir de tus comprobantes o cotizaciones vigentes.', sources:[] },
  { id:'diesel', category:'Viaje', title:'Costo de diésel', icon:Fuel, summary:'Litros y costo esperado por distancia y rendimiento.', calculate:calculateFuel, fields:[field('distance','Distancia por viaje','number',600,'km'),field('efficiency','Rendimiento esperado','number',2.2,'km/L'),field('dieselPrice','Precio real por litro','number',26.5,'MXN/L'),field('idleLiters','Litros en maniobras/ralentí','number',10,'L'),field('trips','Número de viajes','number',1,'viajes')], note:'El precio se captura manualmente para evitar mostrar un promedio nacional como si fuera el precio de tu estación o contrato.', sources:[] },
  { id:'rendimiento', category:'Viaje', title:'Rendimiento de unidad', icon:Gauge, summary:'Calcula km/L, L/100 km y consumo por hora.', calculate:calculateEfficiency, fields:[field('distance','Odómetro final − inicial','number',1200,'km'),field('liters','Litros cargados/consumidos','number',500,'L'),field('engineHours','Horas motor (opcional)','number',0,'h')], note:'Para mayor precisión usa tanque lleno a tanque lleno y el mismo criterio de carga en ambos registros.', sources:[] },
  { id:'utilidad', category:'Viaje', title:'Utilidad por viaje', icon:BadgeDollarSign, summary:'Margen antes de impuestos con desglose de costos.', calculate:calculateTripProfit, fields:[field('revenue','Ingreso del viaje sin IVA','number',30000,'MXN'),field('fuel','Diésel','number',8000,'MXN'),field('tolls','Casetas','number',2500,'MXN'),field('operator','Operador y viáticos','number',1800,'MXN'),field('maintenance','Mantenimiento y llantas','number',1700,'MXN'),field('fixed','Costos fijos asignados','number',1500,'MXN'),field('other','Otros','number',0,'MXN')], note:'Resultado antes de ISR, costo financiero y contingencias no capturadas. Usa importes sin IVA de forma consistente.', sources:[] },
  { id:'operador', category:'Flota', title:'Costo de operador', icon:Users, summary:'Costo mensual, por viaje y por kilómetro.', calculate:calculateOperatorCost, fields:[field('monthlySalary','Salario mensual','number',18000,'MXN'),field('employerBurden','Carga patronal estimada por la empresa','number',35,'%'),field('bonuses','Bonos y comisiones','number',3000,'MXN'),field('allowances','Viáticos','number',5000,'MXN'),field('other','Uniformes, capacitación y otros','number',1000,'MXN'),field('trips','Viajes mensuales','number',12,'viajes'),field('kilometers','Kilómetros mensuales','number',9000,'km')], note:'La carga patronal depende del salario base de cotización, prima de riesgo y prestaciones. Captura el porcentaje calculado por tu nómina o contador.', sources:[] },
  { id:'flota', category:'Flota', title:'Costo mensual de flota', icon:Factory, summary:'Costo total, por unidad y por kilómetro.', calculate:calculateFleetCost, fields:[field('units','Unidades activas','number',5,'unidades'),field('payments','Créditos/arrendamientos mensuales','number',120000,'MXN'),field('insuranceAnnual','Seguros anuales','number',300000,'MXN/año'),field('permitsAnnual','Permisos y verificaciones anuales','number',90000,'MXN/año'),field('maintenance','Mantenimiento mensual','number',80000,'MXN'),field('tires','Llantas mensualizadas','number',45000,'MXN'),field('tracking','GPS y telemetría','number',7500,'MXN'),field('payroll','Nómina operativa mensual','number',180000,'MXN'),field('other','Patio, administración y otros','number',50000,'MXN'),field('kilometers','Kilómetros totales de flota','number',45000,'km')], note:'Mensualiza costos anuales y usa kilómetros efectivamente recorridos. No incluye IVA ni impuestos salvo que los captures dentro de otros costos.', sources:[] },
]

const sources = {
  sat:{label:'SAT · Anexo 8 RMF 2026',url:'https://www.sat.gob.mx/minisitio/NormatividadRMFyRGCE/documentos2026/rmf/anexos/Anexo-8-RMF-2026_DOF-28122025.pdf'},
  lft:{label:'Cámara de Diputados · Ley Federal del Trabajo vigente',url:'https://www.diputados.gob.mx/LeyesBiblio/pdf/LFT.pdf'},
  conasami:{label:'DOF · Salarios mínimos 2026',url:'https://sidof.segob.gob.mx/notas/docFuente/5775534'},
  inegi:{label:`INEGI · UMA 2026 ($${OFFICIAL_VALUES.umaDaily} diaria)`,url:'https://www.inegi.org.mx/contenidos/saladeprensa/boletines/2026/uma/uma2026.pdf'},
}

export default function Calculators(){
  const [selectedId,setSelectedId]=useState('km'),[category,setCategory]=useState('Todas'),[query,setQuery]=useState('')
  const selected=tools.find(item=>item.id===selectedId) || tools[0]
  const initialValues=useMemo(()=>Object.fromEntries(selected.fields.map(item=>[item.key,item.default])),[selected])
  const [values,setValues]=useState(initialValues),[result,setResult]=useState(null)
  useEffect(()=>{setValues(loadSaved(selected.id,initialValues));setResult(null)},[selected,initialValues])
  useEffect(()=>{document.title='Herramientas | Faro Portuario';return()=>{document.title='Faro Portuario | Ecosistema logístico-portuario'}},[])
  const filtered=tools.filter(item=>(category==='Todas'||item.category===category)&&`${item.title} ${item.summary}`.toLowerCase().includes(query.toLowerCase()))
  const calculate=(event)=>{event.preventDefault();const output=selected.calculate(values);setResult(output);localStorage.setItem(`faro-tool-${selected.id}`,JSON.stringify(values))}
  const copy=async()=>{if(!result)return;await navigator.clipboard.writeText(`${selected.title}\nResultado: ${formatTotal(result)}\n${result.rows.map(([label,value])=>`${label}: ${formatRow(selected.id,label,value)}`).join('\n')}\nFaro Portuario · ${OFFICIAL_VALUES.updatedAt}`);toast.success('Resultado copiado')}
  return <div className="min-h-screen bg-[#f4f7f6] text-slate-950"><header className="border-b border-slate-200 bg-[#082f35] text-white"><div className="mx-auto max-w-7xl px-4 py-12 sm:py-16"><nav className="text-xs text-teal-100"><Link to="/">Inicio</Link> <span className="mx-2">/</span> Herramientas</nav><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><Reveal><p className="text-xs font-black uppercase tracking-[.2em] text-teal-300">Centro de cálculo</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.05em] sm:text-6xl">Números claros para operar y decidir.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-slate-300">Nueve calculadoras funcionales. Cada resultado muestra fórmula, supuestos y fuente; tus datos permanecen en este dispositivo.</p></Reveal><div className="grid grid-cols-3 gap-2"><Stat value="9" label="calculadoras"/><Stat value="2026" label="vigencia legal"/><Stat value="0" label="datos inventados"/></div></div></div></header>
  <main className="mx-auto max-w-7xl px-4 py-8"><div className="grid gap-7 lg:grid-cols-[310px_1fr]"><aside><label className="relative block"><Search size={15} className="absolute left-3 top-3.5 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar herramienta" className="h-11 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-teal-700"/></label><div className="mt-3 flex gap-2 overflow-x-auto pb-2 lg:flex-wrap">{['Todas','Laboral y fiscal','Viaje','Flota'].map(item=><button key={item} onClick={()=>setCategory(item)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-[10px] font-black ${category===item?'bg-teal-800 text-white':'border border-slate-200 bg-white text-slate-600'}`}>{item}</button>)}</div><div className="mt-4 space-y-2">{filtered.map(item=><ToolButton key={item.id} item={item} active={item.id===selected.id} onClick={()=>setSelectedId(item.id)}/>)}</div></aside>
  <section className="min-w-0"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_18px_60px_rgba(8,47,53,.08)]"><div className="border-b border-slate-100 p-6 sm:p-8"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-teal-50 text-teal-800"><selected.icon size={21}/></div><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-teal-700">{selected.category}</p><h2 className="mt-1 text-2xl font-black tracking-tight">{selected.title}</h2><p className="mt-2 text-sm text-slate-500">{selected.summary}</p></div></div></div><div className="grid xl:grid-cols-[1fr_360px]"><form onSubmit={calculate} className="p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2">{selected.fields.map(item=><InputField key={item.key} field={item} value={values[item.key]} onChange={value=>setValues(current=>({...current,[item.key]:value}))}/>)}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button className="h-12 flex-1 rounded-xl bg-[#0d5b55] text-sm font-black text-white">Calcular resultado</button><button type="button" onClick={()=>{setValues(initialValues);setResult(null);localStorage.removeItem(`faro-tool-${selected.id}`)}} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 px-5 text-xs font-black"><RotateCcw size={14}/>Restablecer</button></div><div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-950"><b>Alcance:</b> {selected.note}</div></form><ResultPanel selected={selected} result={result} onCopy={copy}/></div></div>
  <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center gap-2"><Check size={17} className="text-teal-700"/><h2 className="font-black">Fuentes y vigencia</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">Parámetros revisados el 14 de julio de 2026. Los cálculos operativos no usan precios promedio: tú capturas los costos reales de tu operación.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{Object.values(sources).map(source=><a key={source.label} href={source.url} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 p-3 text-xs font-bold text-teal-800 hover:border-teal-600">{source.label} ↗</a>)}</div></div></section></div></main></div>
}

function ResultPanel({selected,result,onCopy}){return <aside className="border-t border-slate-100 bg-[#f8faf9] p-6 sm:p-8 xl:border-l xl:border-t-0"><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Resultado estimado</p>{result?<><p className={`mt-3 break-words text-4xl font-black tracking-[-.05em] ${result.total<0?'text-red-700':'text-[#083f3d]'}`}>{formatTotal(result)}</p><div className="mt-6 divide-y divide-slate-200">{result.rows.map(([label,value])=><div key={label} className="flex items-start justify-between gap-4 py-3 text-xs"><span className="text-slate-500">{label}</span><b className="text-right">{formatRow(selected.id,label,value)}</b></div>)}</div><ExtraMetrics result={result}/><button onClick={onCopy} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white py-3 text-xs font-black"><Copy size={14}/>Copiar desglose</button></>:<div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-8 text-center"><Calculator className="mx-auto text-slate-300"/><p className="mt-4 text-sm font-black">Completa los datos</p><p className="mt-2 text-xs leading-5 text-slate-500">El desglose y las métricas aparecerán aquí.</p></div>}<p className="mt-6 text-[10px] leading-4 text-slate-400">Estimación informativa; no sustituye CFDI de nómina, cotización, contrato, contabilidad ni asesoría legal o fiscal.</p></aside>}
function ExtraMetrics({result}){const metrics=[];if(result.effectiveRate!=null)metrics.push(['Tasa efectiva',`${number.format(result.effectiveRate)}%`]);if(result.margin!=null)metrics.push(['Margen',`${number.format(result.margin)}%`]);if(result.tripTotal!=null)metrics.push(['Total del viaje',currency.format(result.tripTotal)]);if(result.perTrip!=null)metrics.push(['Costo por viaje',currency.format(result.perTrip)]);if(result.perUnit!=null)metrics.push(['Costo por unidad',currency.format(result.perUnit)]);if(result.perKm!=null)metrics.push(['Costo por km',currency.format(result.perKm)]);if(result.liters!=null)metrics.push(['Litros totales',number.format(result.liters)]);if(!metrics.length)return null;return <div className="mt-5 grid grid-cols-2 gap-2">{metrics.map(([label,value])=><div key={label} className="rounded-lg bg-white p-3"><p className="text-[9px] font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>)}</div>}
function InputField({field,value,onChange}){if(field.type==='checkbox')return <label className="flex min-h-14 items-center gap-3 rounded-xl border border-slate-200 p-3 text-xs font-black"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)} className="h-4 w-4 accent-teal-700"/>{field.label}</label>;return <label className="block"><span className="text-[10px] font-black uppercase tracking-[.1em] text-slate-500">{field.label}</span><div className="relative mt-1">{field.type==='select'?<select value={value} onChange={e=>onChange(e.target.value)} className="input-op">{field.options.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>:<input required type={field.type} min={field.type==='number'?0:undefined} step={field.type==='number'?'any':undefined} value={value} onChange={e=>onChange(e.target.value)} className="input-op pr-16"/>}{field.unit&&<span className="pointer-events-none absolute right-3 top-3 text-[10px] font-bold text-slate-400">{field.unit}</span>}</div></label>}
function ToolButton({item,active,onClick}){const Icon=item.icon;return <button onClick={onClick} className={`w-full rounded-xl border p-4 text-left transition ${active?'border-teal-700 bg-teal-50 shadow-sm':'border-slate-200 bg-white hover:border-teal-300'}`}><div className="flex gap-3"><Icon size={17} className={active?'text-teal-800':'text-slate-400'}/><div><p className="text-xs font-black">{item.title}</p><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-500">{item.summary}</p></div></div></button>}
function Stat({value,label}){return <div className="rounded-xl border border-white/10 bg-white/5 p-3 text-center"><p className="text-xl font-black text-teal-200">{value}</p><p className="mt-1 text-[9px] uppercase text-slate-400">{label}</p></div>}
function formatTotal(result){return result.unit==='km/L'?`${number.format(result.total)} km/L`:result.unit==='$/km'?`${currency.format(result.total)}/km`:currency.format(result.total)}
function formatRow(toolId,label,value){if(toolId==='rendimiento'){if(label.includes('Kilómetros'))return `${number.format(value)} km`;if(label.includes('100 km'))return `${number.format(value)} L/100 km`;if(label.includes('hora'))return `${number.format(value)} L/h`;return `${number.format(value)} L`}if(toolId==='diesel'&&label.includes('Litros'))return `${number.format(value)} L`;return currency.format(value)}
function field(key,label,type,defaultValue,unit){return{key,label,type,default:defaultValue,unit}}
function select(key,label,options,defaultValue){return{key,label,type:'select',options,default:defaultValue}}
function check(key,label,defaultValue){return{key,label,type:'checkbox',default:defaultValue}}
function loadSaved(id,fallback){try{const saved=localStorage.getItem(`faro-tool-${id}`);return saved?{...fallback,...JSON.parse(saved)}:fallback}catch{return fallback}}
