import { useEffect, useState } from 'react'
import { AlertOctagon, Anchor, Cable, CircleAlert, Container, Map, Route, Satellite } from 'lucide-react'
import toast from 'react-hot-toast'
import OperationalWorkspace, { EmptyOperational, statusTone } from '../components/operations/OperationalWorkspace.jsx'
import { useOperationalContext } from '../hooks/useOperationalContext.js'
import { operationsApi } from '../lib/operationsApi.js'
import Reveal from '../components/ui/Reveal.jsx'

export default function ControlTower(){
 const context=useOperationalContext(),[data,setData]=useState(null)
 useEffect(()=>{setData(null);if(context.companyId)operationsApi.tower(context.companyId).then(setData).catch(e=>toast.error(e.message))},[context.companyId])
 const critical=data?.alerts?.filter(x=>x.severity==='critical').length||0, blocked=data?.routes?.filter(x=>x.status==='blocked').length||0
 return <OperationalWorkspace title="Torre de Control" eyebrow="Visibilidad operativa" description="Una vista integrada de rutas, seguridad, aduanas, citas, incidentes y fuentes conectadas. Los vacíos de información permanecen visibles como tales." updatedAt={data?.generated_at} {...context}>
 {!context.companyId?<EmptyOperational title={context.loading?'Cargando empresas':'Sin empresa operativa'} text={context.error||'Selecciona una empresa para consultar su torre de control.'}/>:!data?<EmptyOperational title="Preparando torre de control" text="Consultando únicamente las fuentes y registros disponibles para esta empresa."/>:<>
  <Reveal className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric icon={Route} value={data.routes.length} label="Rutas activas" tone="teal"/><Metric icon={AlertOctagon} value={blocked} label="Rutas bloqueadas" tone={blocked?'red':'slate'}/><Metric icon={Container} value={data.customs.length} label="Operaciones aduanales"/><Metric icon={Anchor} value={data.appointments.length} label="Citas portuarias"/><Metric icon={CircleAlert} value={critical} label="Alertas críticas" tone={critical?'red':'slate'}/><Metric icon={Cable} value={data.providers.filter(x=>x.status==='healthy').length} label="Fuentes saludables"/></Reveal>
  <div className="mt-5 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
   <section className="overflow-hidden rounded-2xl border border-slate-200 bg-[#0b2631]"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4 text-white"><div><h2 className="flex items-center gap-2 font-black"><Map size={17}/>Mapa operativo</h2><p className="mt-1 text-xs text-slate-400">Representación basada en registros con coordenadas disponibles</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-[9px] font-black uppercase">Sin simulación</span></div><div className="relative min-h-[430px] overflow-hidden bg-[linear-gradient(rgba(255,255,255,.04)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.04)_1px,transparent_1px)] bg-[size:42px_42px] p-6"><div className="absolute inset-0 bg-[radial-gradient(circle_at_28%_38%,rgba(20,184,166,.16),transparent_28%),radial-gradient(circle_at_70%_65%,rgba(245,158,11,.12),transparent_25%)]"/><div className="relative grid min-h-[380px] place-items-center rounded-2xl border border-dashed border-white/15 text-center"><div><Satellite size={34} className="mx-auto text-teal-300"/><p className="mt-4 font-black text-white">Mapa listo para fuentes GPS y rutas</p><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-slate-400">No se dibujan unidades ni incidentes inexistentes. Al conectar GPS o cargar coordenadas validadas aparecerán aquí con fuente y actualización.</p></div></div></div></section>
   <aside className="space-y-5"><Panel title="Alertas abiertas" count={data.alerts.length}>{data.alerts.length?data.alerts.slice(0,6).map(x=><div key={x.id} className="border-b border-slate-100 py-3 last:border-0"><div className="flex items-center justify-between gap-2"><p className="text-xs font-black">{x.title}</p><span className={`rounded-full border px-2 py-0.5 text-[8px] font-black uppercase ${statusTone(x.severity)}`}>{x.severity}</span></div><p className="mt-1 text-[11px] leading-5 text-slate-500">{x.message}</p><p className="mt-1 text-[9px] font-bold text-slate-400">Fuente: {x.source_name} · {x.confidence}%</p></div>):<SmallEmpty text="No hay alertas abiertas registradas."/>}</Panel><Panel title="Fuentes" count={data.providers.length}>{data.providers.length?data.providers.map(x=><div key={x.id} className="flex items-center justify-between border-b border-slate-100 py-3 last:border-0"><div><p className="text-xs font-black">{x.name}</p><p className="mt-1 text-[9px] uppercase text-slate-400">{x.provider_type} · {x.source_class}</p></div><span className={`h-2.5 w-2.5 rounded-full ${x.status==='healthy'?'bg-emerald-500':x.status==='degraded'?'bg-amber-500':'bg-slate-300'}`} title={x.status}/></div>):<SmallEmpty text="No hay integraciones activas. El sistema continúa con captura interna y manual identificada."/>}</Panel></aside>
  </div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="Rutas y cumplimiento" count={data.routes.length}>{data.routes.length?data.routes.slice(0,8).map(x=><Row key={x.id} title={x.name} detail={`${x.origin} → ${x.destination}`} status={x.status} updated={x.updated_at}/>):<SmallEmpty text="No existen rutas activas."/>}</Panel><Panel title="Control aduanal" count={data.customs.length}>{data.customs.length?data.customs.slice(0,8).map(x=><Row key={x.id} title={x.reference} detail={`${x.container_number||'Sin contenedor'} · ${x.status_label}`} status={x.status_code==='released'?'approved':x.status_code==='incident'?'blocked':'conditional'} updated={x.updated_at}/>):<SmallEmpty text="No existen operaciones aduanales."/>}</Panel></div>
  <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><strong>Transparencia:</strong> {data.disclaimer}</div>
 </>}
 </OperationalWorkspace>
}
function Metric({icon:Icon,value,label,tone='slate'}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><Icon size={17} className={tone==='red'?'text-red-600':'text-teal-700'}/><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-[11px] text-slate-500">{label}</p></div>}
function Panel({title,count,children}){return <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-3"><h2 className="text-sm font-black">{title}</h2><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-black">{count}</span></div><div>{children}</div></section>}
function Row({title,detail,status,updated}){return <div className="flex items-center justify-between gap-4 border-b border-slate-100 py-3 last:border-0"><div className="min-w-0"><p className="truncate text-xs font-black">{title}</p><p className="mt-1 truncate text-[11px] text-slate-500">{detail}</p><p className="mt-1 text-[9px] text-slate-400">{new Date(updated).toLocaleString('es-MX')}</p></div><span className={`shrink-0 rounded-full border px-2 py-1 text-[8px] font-black uppercase ${statusTone(status)}`}>{status}</span></div>}
function SmallEmpty({text}){return <p className="py-8 text-center text-xs leading-5 text-slate-400">{text}</p>}
