import { useEffect, useState } from 'react'
import { Anchor, CalendarClock, Container, FileCheck2, Plus } from 'lucide-react'
import toast from 'react-hot-toast'
import OperationalWorkspace, { EmptyOperational } from '../components/operations/OperationalWorkspace.jsx'
import { useOperationalContext } from '../hooks/useOperationalContext.js'
import { operationsApi } from '../lib/operationsApi.js'

const statuses = [['documentation_pending','Documentación pendiente'],['documents_review','Documentación en revisión'],['customs_entry_validated','Pedimento validado'],['customs_entry_paid','Pedimento pagado'],['cargo_arrived','Mercancía arribada'],['container_discharged','Contenedor descargado'],['modulation_pending','Modulación pendiente'],['customs_inspection','Reconocimiento aduanero'],['released','Mercancía liberada'],['appointment_confirmed','Cita confirmada'],['unit_entered','Unidad ingresó'],['gate_out','Unidad salió del recinto'],['delivery_completed','Entrega completada'],['incident','Incidencia aduanal']]
const initial={reference:'',operation_type:'import',customs_name:'Aduana de Manzanillo',port_name:'Puerto de Manzanillo',terminal_name:'',broker_name:'',container_number:'',booking:'',customs_entry:'',status_source:'Captura empresarial',source_class:'manual',confidence:50,next_action:'',free_days_until:'',responsible_name:''}
const initialAppointment={port_name:'Puerto de Manzanillo',terminal_name:'',operation_type:'ingreso',container_number:'',booking:'',vehicle_plate:'',driver_name:'',window_start:'',window_end:'',source_name:'Solicitud empresarial',source_class:'manual'}

export default function CustomsControl(){
 const context=useOperationalContext(),[operations,setOperations]=useState([]),[appointments,setAppointments]=useState([]),[form,setForm]=useState(initial),[appointment,setAppointment]=useState(initialAppointment),[showAppointment,setShowAppointment]=useState(false),[selected,setSelected]=useState(null),[event,setEvent]=useState({status_code:'documents_review',status_label:'Documentación en revisión',source_name:'Captura empresarial',source_class:'manual',confidence:50,comment:'',next_action:''}),[busy,setBusy]=useState(false)
 const load=()=>context.companyId&&Promise.all([operationsApi.customs(context.companyId),operationsApi.appointments(context.companyId)]).then(([x,a])=>{setOperations(x.data);setAppointments(a.data)}).catch(e=>toast.error(e.message)); useEffect(load,[context.companyId])
 const submit=async(e)=>{e.preventDefault();setBusy(true);try{await operationsApi.createCustoms(context.companyId,form);setForm(initial);toast.success('Operación aduanal registrada');load()}catch(x){toast.error(x.message)}finally{setBusy(false)}}
 const addEvent=async(e)=>{e.preventDefault();setBusy(true);try{await operationsApi.addCustomsEvent(context.companyId,selected.id,event);toast.success('Timeline actualizado');setSelected(null);load()}catch(x){toast.error(x.message)}finally{setBusy(false)}}
 const submitAppointment=async(e)=>{e.preventDefault();setBusy(true);try{await operationsApi.createAppointment(context.companyId,appointment);setAppointment(initialAppointment);setShowAppointment(false);toast.success('Solicitud de cita registrada');load()}catch(x){toast.error(x.message)}finally{setBusy(false)}}
 return <OperationalWorkspace title="Centro de Control Aduanal y Portuario" eyebrow="Comercio exterior" description="Concentra estados, responsables, evidencias y próximas acciones. Cada actualización identifica su fuente y nivel de confianza." {...context}>
 {!context.companyId?<EmptyOperational title={context.loading?'Cargando empresas':'Sin empresa operativa'} text={context.error||'Selecciona una empresa para administrar operaciones aduanales.'}/>:<div className="grid gap-6 xl:grid-cols-[390px_1fr]">
  <form onSubmit={submit} className="self-start rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Anchor size={18} className="text-teal-700"/><h2 className="font-black">Nueva operación</h2></div><div className="mt-5 grid gap-3">{[['reference','Referencia interna'],['container_number','Contenedor'],['booking','Booking'],['customs_entry','Pedimento'],['broker_name','Agente aduanal'],['terminal_name','Terminal'],['responsible_name','Responsable'],['next_action','Próxima acción']].map(([key,label])=><Field key={key} label={label}><input required={key==='reference'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="input-op"/></Field>)}<div className="grid grid-cols-2 gap-2"><Field label="Operación"><select value={form.operation_type} onChange={e=>setForm({...form,operation_type:e.target.value})} className="input-op"><option value="import">Importación</option><option value="export">Exportación</option><option value="interior">Aduana interior</option><option value="border">Frontera</option><option value="airport">Aeropuerto</option></select></Field><Field label="Días libres hasta"><input type="date" value={form.free_days_until} onChange={e=>setForm({...form,free_days_until:e.target.value})} className="input-op"/></Field></div><div className="grid grid-cols-2 gap-2"><Field label="Tipo de fuente"><select value={form.source_class} onChange={e=>setForm({...form,source_class:e.target.value})} className="input-op"><option value="manual">Captura manual</option><option value="internal">Dato interno</option><option value="third_party">Tercero</option><option value="official">Oficial autorizado</option></select></Field><Field label="Confianza %"><input type="number" min="0" max="100" value={form.confidence} onChange={e=>setForm({...form,confidence:e.target.value})} className="input-op"/></Field></div></div><button disabled={busy} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#0d5b55] text-xs font-black text-white"><Plus size={15}/>Registrar operación</button></form>
  <section><div className="grid gap-3 sm:grid-cols-3"><Metric icon={Container} value={operations.length} label="Operaciones"/><Metric icon={FileCheck2} value={operations.filter(x=>x.status_code==='released').length} label="Liberadas"/><button onClick={()=>setShowAppointment(true)} className="text-left"><Metric icon={CalendarClock} value={appointments.filter(x=>['requested','confirmed'].includes(x.status)).length} label="Citas activas · agregar"/></button></div><div className="mt-5 space-y-4">{operations.length?operations.map(op=><article key={op.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-teal-700">{op.operation_type} · {op.reference}</p><h2 className="mt-2 text-lg font-black">{op.status_label}</h2><p className="mt-2 text-sm text-slate-600">{op.container_number||'Sin contenedor'} · {op.customs_name||op.port_name||'Ubicación pendiente'}</p><p className="mt-2 text-xs text-slate-400">Fuente: {op.status_source} ({labelSource(op.source_class)}) · Confianza {op.confidence}% · {new Date(op.updated_at).toLocaleString('es-MX')}</p></div><button onClick={()=>setSelected(op)} className="h-10 rounded-lg border border-slate-200 px-4 text-xs font-black">Actualizar estado</button></div><div className="mt-5 border-l-2 border-slate-200 pl-5">{[...(op.customs_events||[])].sort((a,b)=>new Date(b.occurred_at)-new Date(a.occurred_at)).slice(0,4).map(item=><div key={item.id} className="relative pb-4 last:pb-0"><span className="absolute -left-[25px] top-1 h-2 w-2 rounded-full bg-teal-600 ring-4 ring-white"/><p className="text-xs font-black">{item.status_label}</p><p className="mt-1 text-[11px] text-slate-500">{new Date(item.occurred_at).toLocaleString('es-MX')} · {item.source_name} · {item.confidence}%</p>{item.comment&&<p className="mt-1 text-xs text-slate-600">{item.comment}</p>}</div>)}</div></article>):<EmptyOperational title="Sin operaciones aduanales" text="Registra una referencia para comenzar su timeline. Los estados capturados manualmente nunca se mostrarán como oficiales."/>}</div></section>
 </div>}
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><form onSubmit={addEvent} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-black">Actualizar {selected.reference}</h2><div className="mt-5 grid gap-3"><Field label="Nuevo estado"><select value={event.status_code} onChange={e=>{const found=statuses.find(x=>x[0]===e.target.value);setEvent({...event,status_code:found[0],status_label:found[1]})}} className="input-op">{statuses.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></Field><Field label="Fuente"><input required value={event.source_name} onChange={e=>setEvent({...event,source_name:e.target.value})} className="input-op"/></Field><div className="grid grid-cols-2 gap-2"><Field label="Tipo"><select value={event.source_class} onChange={e=>setEvent({...event,source_class:e.target.value})} className="input-op"><option value="manual">Manual</option><option value="internal">Interna</option><option value="third_party">Tercero</option><option value="official">Oficial autorizado</option></select></Field><Field label="Confianza %"><input type="number" min="0" max="100" value={event.confidence} onChange={e=>setEvent({...event,confidence:e.target.value})} className="input-op"/></Field></div><Field label="Comentario"><textarea value={event.comment} onChange={e=>setEvent({...event,comment:e.target.value})} className="input-op min-h-20"/></Field><Field label="Próxima acción"><input value={event.next_action} onChange={e=>setEvent({...event,next_action:e.target.value})} className="input-op"/></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setSelected(null)} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-black">Cancelar</button><button disabled={busy} className="rounded-lg bg-[#0d5b55] px-4 py-2 text-xs font-black text-white">Guardar evento</button></div></form></div>}
 {showAppointment&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4" role="dialog" aria-modal="true"><form onSubmit={submitAppointment} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-lg font-black">Solicitar cita portuaria</h2><p className="mt-2 text-xs text-slate-500">La solicitud no se considera confirmada por la terminal.</p><div className="mt-5 grid gap-3">{[['terminal_name','Terminal'],['container_number','Contenedor'],['vehicle_plate','Placa'],['driver_name','Operador']].map(([key,label])=><Field key={key} label={label}><input value={appointment[key]} onChange={e=>setAppointment({...appointment,[key]:e.target.value})} className="input-op"/></Field>)}<div className="grid grid-cols-2 gap-2"><Field label="Inicio"><input required type="datetime-local" value={appointment.window_start} onChange={e=>setAppointment({...appointment,window_start:e.target.value})} className="input-op"/></Field><Field label="Fin"><input required type="datetime-local" value={appointment.window_end} onChange={e=>setAppointment({...appointment,window_end:e.target.value})} className="input-op"/></Field></div></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={()=>setShowAppointment(false)} className="rounded-lg border border-slate-200 px-4 py-2 text-xs font-black">Cancelar</button><button disabled={busy} className="rounded-lg bg-[#0d5b55] px-4 py-2 text-xs font-black text-white">Registrar solicitud</button></div></form></div>}
 <p className="mt-6 text-xs leading-5 text-slate-500">Estado reportado por la fuente conectada. Requiere confirmación del agente o autoridad cuando corresponda.</p>
 </OperationalWorkspace>
}
function Field({label,children}){return <label className="block text-[10px] font-black uppercase tracking-[.12em] text-slate-500">{label}{children}</label>}
function Metric({icon:Icon,value,label}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><Icon size={17} className="text-teal-700"/><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>}
function labelSource(value){return {official:'oficial autorizado',third_party:'tercero',internal:'interno',manual:'captura manual'}[value]||value}
