import { useCallback, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowRight, Clock3, ExternalLink, Gauge, MapPin, Navigation, RadioTower, Route, ShieldAlert, Truck } from 'lucide-react'
import FreightRouteMap from '../components/ui/FreightRouteMap.jsx'
import { googleDirectionsUrl, OFFICIAL_ROUTES_SOURCE, routeOptions, wazeDirectionsUrl } from '../data/manzanilloRoutes.js'

function duration(seconds) {
  if (!seconds) return 'Por calcular'
  const minutes = Math.round(seconds / 60)
  return minutes >= 60 ? `${Math.floor(minutes/60)} h ${minutes%60} min` : `${minutes} min`
}

export default function LongHaulRoutes() {
  const [direction, setDirection] = useState('enter')
  const options = useMemo(() => routeOptions(direction), [direction])
  const [selectedId, setSelectedId] = useState('salada')
  const [summaries, setSummaries] = useState({})
  const selected = options.find(route => route.id === selectedId) || options[0]
  const updateSummary = useCallback((summary) => setSummaries(current => ({ ...current, [`${direction}:${selectedId}`]: summary })), [direction, selectedId])
  const summary = summaries[`${direction}:${selected.id}`]

  return <div className="min-h-screen bg-[#f3f7f6] text-slate-950">
    <section className="relative isolate overflow-hidden bg-[#061e26] text-white"><div className="port-grid absolute inset-0 -z-10 opacity-30"/><div className="absolute -right-20 top-0 -z-10 h-80 w-80 rounded-full bg-teal-400/10 blur-3xl"/><div className="mx-auto max-w-7xl px-4 py-10 sm:py-14"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-teal-300/25 bg-teal-300/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-teal-200"><span className="h-2 w-2 animate-pulse rounded-full bg-teal-300 shadow-[0_0_12px_#5eead4]"/> Rutas foráneas</div><h1 className="mt-5 text-4xl font-black tracking-[-.055em] sm:text-6xl">Elige cómo entrar o salir de Manzanillo.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">Compara corredores publicados por el Gobierno de Colima y visualiza el recorrido con tráfico de Google cuando esté disponible.</p></div><div className="mt-8 inline-grid grid-cols-2 rounded-2xl border border-white/10 bg-black/25 p-1.5 backdrop-blur" role="group" aria-label="Sentido de la ruta">{[['enter','Entrar a Manzanillo'],['exit','Salir de Manzanillo']].map(([value,label])=><button key={value} onClick={()=>setDirection(value)} aria-pressed={direction===value} className={`min-h-12 rounded-xl px-4 text-xs font-black transition sm:px-7 ${direction===value?'bg-teal-300 text-[#062b2f] shadow-[0_0_28px_rgba(45,212,191,.25)]':'text-slate-300 hover:text-white'}`}>{label}</button>)}</div></div></section>

    <main className="mx-auto max-w-7xl px-4 py-8 sm:py-10"><div className="grid gap-6 lg:grid-cols-[360px_minmax(0,1fr)]">
      <aside><div className="rounded-3xl border border-slate-200 bg-white p-4 shadow-[0_18px_55px_rgba(8,31,44,.06)]"><div className="flex items-center justify-between px-1"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-teal-700">Alternativas</p><h2 className="mt-1 text-lg font-black">Colima ↔ Manzanillo</h2></div><Route className="text-teal-700" size={20}/></div><div className="mt-4 space-y-2">{options.map((route,index)=>{const itemSummary=summaries[`${direction}:${route.id}`]; const active=route.id===selected.id; return <button key={route.id} onClick={()=>setSelectedId(route.id)} aria-pressed={active} className={`zone-reveal w-full rounded-2xl border p-4 text-left transition ${active?'border-teal-600 bg-teal-50 shadow-[0_10px_25px_rgba(13,91,85,.10)]':'border-slate-200 hover:border-teal-300'}`} style={{animationDelay:`${index*40}ms`}}><div className="flex items-start gap-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl text-xs font-black ${active?'bg-[#0d5b55] text-white':'bg-slate-100 text-slate-500'}`}>{String(index+1).padStart(2,'0')}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="font-black">{route.name}</p>{route.id==='salada'&&<span className="rounded-full bg-emerald-100 px-2 py-1 text-[8px] font-black uppercase text-emerald-800">Referencia principal</span>}</div><p className="mt-1 text-[10px] text-slate-500">{route.character}</p>{itemSummary&&<p className="mt-2 text-[10px] font-black text-teal-800">{duration(itemSummary.seconds)} · {(itemSummary.distance/1000).toFixed(0)} km</p>}</div></div></button>})}</div></div>
        <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><ShieldAlert size={18} className="mt-0.5 shrink-0 text-amber-700"/><p className="text-[10px] leading-5 text-amber-900"><b>Referencia vial, no autorización para carga.</b> Confirma dimensiones, peso, configuración, cierres, casetas y permisos con la autoridad y tu empresa antes de asignar la unidad.</p></div></div>
      </aside>

      <section className="min-w-0"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white p-3 shadow-[0_20px_60px_rgba(8,31,44,.08)]"><FreightRouteMap route={selected} onSummary={updateSummary}/><div className="grid gap-3 p-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black">Ruta {selected.name}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-black text-slate-600">{selected.origin.label} → {selected.destination.label}</span></div><div className="mt-2 flex flex-wrap gap-4 text-[10px] font-bold text-slate-500"><span className="flex items-center gap-1.5"><Clock3 size={13}/>{summary?duration(summary.seconds):'Calcula al abrir el mapa'}</span><span className="flex items-center gap-1.5"><Gauge size={13}/>{summary?`${(summary.distance/1000).toFixed(0)} km`:'Distancia pendiente'}</span><span className="flex items-center gap-1.5"><RadioTower size={13}/> Tráfico del proveedor</span></div></div><div className="flex gap-2"><a href={googleDirectionsUrl(selected)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-4 text-[10px] font-black text-slate-700 hover:border-teal-500"><MapPin size={14}/> Google</a><a href={wazeDirectionsUrl(selected)} target="_blank" rel="noopener noreferrer" className="port-glow-button inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#0d5b55] px-4 text-[10px] font-black text-white"><Navigation size={14}/> Waze</a></div></div></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-3"><Info icon={Truck} title="Antes de asignar" text="Valida unidad, configuración y peso en Rutas inteligentes." link="/rutas-inteligentes"/><Info icon={RadioTower} title="Antes de llegar" text="Consulta accesos y reportes de la comunidad." link="/pulso-portuario"/><Info icon={AlertTriangle} title="Durante el viaje" text="Revisa avisos oficiales y evita decidir con datos vencidos." link="/noticias"/></div>
        <div className="mt-5 flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-[10px] leading-5 text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>Corredores basados en la publicación de Rutas Alternas del Gobierno del Estado de Colima. Faro Portuario añade comparación, tráfico y accesos; no altera la fuente.</p><a href={OFFICIAL_ROUTES_SOURCE} target="_blank" rel="noopener noreferrer" className="inline-flex shrink-0 items-center gap-1 font-black text-teal-800">Consultar fuente oficial <ExternalLink size={12}/></a></div>
      </section>
    </div></main>
  </div>
}

function Info({icon:Icon,title,text,link}){return <Link to={link} className="group rounded-2xl border border-slate-200 bg-white p-4 transition hover:-translate-y-0.5 hover:border-teal-400"><Icon size={17} className="text-teal-700"/><h3 className="mt-3 text-xs font-black">{title}</h3><p className="mt-1 text-[10px] leading-5 text-slate-500">{text}</p><span className="mt-3 inline-flex items-center gap-1 text-[9px] font-black text-teal-800">Abrir módulo <ArrowRight size={11} className="transition group-hover:translate-x-1"/></span></Link>}
