import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import toast from 'react-hot-toast'
import { ArrowRight, BadgeCheck, Box, Check, Image as ImageIcon, MapPin, Package, Plus, ShieldCheck, Store, X } from 'lucide-react'
import { marketplaceApi } from '../lib/marketplaceApi.js'
import { useAuthStore } from '../stores/authStore.js'

const FALLBACK_PLANS = [
  { code:'marketplace_starter', name:'Vitrina 3', monthly_price:599, product_limit:3, description:'Para comenzar a vender o rentar hasta 3 productos.' },
  { code:'marketplace_growth', name:'Catálogo 10', monthly_price:799, product_limit:10, description:'Publica de 4 a 10 productos con mayor capacidad comercial.' },
  { code:'marketplace_scale', name:'Escala', monthly_price:1399, product_limit:null, description:'Publica desde 11 productos sin límite máximo.' },
]

export default function Marketplace() {
  const user = useAuthStore(s => s.user)
  const [selectedCompany, setSelectedCompany] = useState('')
  const [showForm, setShowForm] = useState(false)
  const { data = {}, isLoading } = useQuery({ queryKey:['marketplace-public'], queryFn:marketplaceApi.list })
  const { data: context } = useQuery({ queryKey:['marketplace-context',user?.id], queryFn:marketplaceApi.context, enabled:Boolean(user), retry:false })
  const plans = data.plans?.length ? data.plans : FALLBACK_PLANS
  const companies = context?.companies || []
  const companyId = selectedCompany || companies[0]?.id || ''
  const company = companies.find(item => item.id === companyId) || companies[0]

  async function contract(planCode) {
    if (!user) return toast.error('Primero crea tu cuenta o inicia sesión')
    if (!companyId) return toast.error('Registra tu empresa o actividad empresarial para contratar')
    try {
      const result = await marketplaceApi.checkout(planCode, companyId)
      window.location.assign(result.url)
    } catch (error) { toast.error(error.message) }
  }

  return <div className="min-h-screen bg-[#f4f7f6] text-slate-950">
    <section className="overflow-hidden bg-[#062f33] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:px-8 lg:py-20"><div><span className="inline-flex items-center gap-2 rounded-full border border-teal-200/20 bg-white/5 px-3 py-2 text-[10px] font-black uppercase tracking-[.18em] text-teal-200"><Store size={14}/> Marketplace logístico verificado</span><h1 className="mt-7 text-4xl font-black tracking-[-.055em] sm:text-6xl">Compra, vende y renta equipo para operar.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300">Un espacio comercial para unidades, remolques, refacciones, equipo portuario y servicios del sector. Cada vendedor debe registrarse y verificar su identidad empresarial.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#productos" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#f7b63d] px-5 text-sm font-black text-[#062f33]">Explorar productos <ArrowRight size={16}/></a><button onClick={() => user ? setShowForm(true) : toast.error('Regístrate para publicar')} className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/20 px-5 text-sm font-black"><Plus size={16}/> Publicar producto</button></div></div><div className="grid content-end gap-3 sm:grid-cols-2"><Trust icon={ShieldCheck} title="Vendedores verificados" text="Empresa o persona física con validación previa."/><Trust icon={Package} title="Planes transparentes" text="Desde $599 MXN mensuales, sin comisión por venta."/><Trust icon={BadgeCheck} title="Contacto directo" text="Teléfono y WhatsApp del anunciante."/><Trust icon={Box} title="Sector especializado" text="Equipo y servicios para logística y puerto."/></div></div></section>

    <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
      <section id="productos"><div className="flex items-end justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-teal-700">Oferta publicada</p><h2 className="mt-2 text-3xl font-black tracking-tight">Marketplace Faro</h2></div>{user && companies.length > 0 && <select value={companyId} onChange={e=>setSelectedCompany(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold">{companies.map(item=><option key={item.id} value={item.id}>{item.trade_name}</option>)}</select>}</div>
        {isLoading ? <div className="mt-7 grid gap-5 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-80 animate-pulse rounded-3xl bg-white"/>)}</div> : data.items?.length ? <div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.items.map(item=><ProductCard key={item.id} item={item}/>)}</div> : <div className="mt-7 rounded-3xl border border-dashed border-teal-300 bg-white px-6 py-14 text-center"><Package size={38} className="mx-auto text-teal-700"/><h3 className="mt-5 text-xl font-black">Sé de los primeros en publicar</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-500">El catálogo abre con vendedores verificados. Registra tu empresa o actividad empresarial, elige una membresía y publica tus productos.</p><button onClick={()=>user ? setShowForm(true) : toast.error('Primero crea tu cuenta')} className="mt-6 min-h-11 rounded-xl bg-[#0f766e] px-5 text-sm font-black text-white">Quiero vender</button></div>}
      </section>

      <section id="planes" className="mt-16"><div className="max-w-3xl"><p className="text-[10px] font-black uppercase tracking-[.2em] text-teal-700">Membresía mensual</p><h2 className="mt-2 text-3xl font-black tracking-tight">Publica según el tamaño de tu catálogo</h2><p className="mt-3 text-sm leading-6 text-slate-500">Precios en MXN. Requiere registro y empresa o persona física verificada. No cobramos comisión por cada producto.</p></div><div className="mt-8 grid gap-4 lg:grid-cols-3">{plans.map((plan,index)=><article key={plan.code} className={`flex flex-col rounded-3xl border bg-white p-6 ${index===1?'border-teal-600 ring-4 ring-teal-50':'border-slate-200'}`}><p className="text-[10px] font-black uppercase tracking-[.16em] text-teal-700">{plan.product_limit ? `Hasta ${plan.product_limit} productos` : '11 a ilimitados'}</p><h3 className="mt-3 text-xl font-black">{plan.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{plan.description}</p><p className="mt-6 text-4xl font-black tracking-tight">${Number(plan.monthly_price).toLocaleString('es-MX')} <span className="text-xs text-slate-400">MXN / mes</span></p><ul className="mt-6 flex-1 space-y-3 text-sm text-slate-600"><li className="flex gap-2"><Check size={16} className="text-teal-700"/>Perfil comercial verificado</li><li className="flex gap-2"><Check size={16} className="text-teal-700"/>Contacto por teléfono y WhatsApp</li><li className="flex gap-2"><Check size={16} className="text-teal-700"/>Publicaciones activas durante el mes</li></ul><button onClick={()=>contract(plan.code)} className="mt-7 min-h-12 rounded-xl bg-[#062f33] px-4 text-sm font-black text-white">Elegir {plan.name}</button></article>)}</div></section>
      {!user && <section className="mt-12 rounded-3xl bg-[#f7b63d] p-7 text-[#062f33] sm:flex sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">Para vender, primero identifícate.</h2><p className="mt-2 text-sm font-medium">El registro es gratuito; la membresía solo se cobra al publicar.</p></div><Link to="/register" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#062f33] px-5 text-sm font-black text-white sm:mt-0">Crear cuenta</Link></section>}
    </main>
    {showForm && <ProductForm company={company} onClose={()=>setShowForm(false)}/>}
  </div>
}

function Trust({icon:Icon,title,text}) { return <div className="rounded-2xl border border-white/10 bg-white/5 p-5"><Icon size={21} className="text-teal-200"/><h2 className="mt-4 text-sm font-black">{title}</h2><p className="mt-2 text-xs leading-5 text-slate-300">{text}</p></div> }
function ProductCard({item}) { const image=item.image_urls?.[0]; return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid h-48 place-items-center bg-slate-100">{image?<img src={image} alt={item.title} className="h-full w-full object-cover"/>:<ImageIcon className="text-slate-300" size={42}/>}</div><div className="p-5"><p className="text-[10px] font-black uppercase tracking-wider text-teal-700">{item.category}</p><h3 className="mt-2 text-lg font-black">{item.title}</h3><p className="mt-3 text-2xl font-black">{item.price==null?'Precio a consultar':`$${Number(item.price).toLocaleString('es-MX')} MXN`}</p><p className="mt-3 flex items-center gap-1.5 text-xs text-slate-500"><MapPin size={13}/>{item.city}, {item.state}</p></div></article> }

function ProductForm({company,onClose}) {
  const qc=useQueryClient(); const [loading,setLoading]=useState(false)
  const [form,setForm]=useState({title:'',description:'',category:'equipo',listing_type:'sale',price:'',price_includes_vat:false,city:'Manzanillo',state:'Colima',image_url:'',contact_phone:'',contact_whatsapp:''})
  const canPublish=useMemo(()=>company?.status==='verified' && company?.subscription,[company])
  async function submit(event){event.preventDefault();if(!company)return toast.error('Registra una empresa o persona física');setLoading(true);try{await marketplaceApi.publish(company.id,{...form,image_urls:form.image_url?[form.image_url]:[]});toast.success('Producto publicado');qc.invalidateQueries({queryKey:['marketplace-public']});onClose()}catch(error){toast.error(error.message)}finally{setLoading(false)}}
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/65 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-teal-700">Nueva publicación</p><h2 className="mt-2 text-2xl font-black">Publicar producto</h2></div><button onClick={onClose} className="h-10 w-10 rounded-full border border-slate-200"><X className="mx-auto" size={17}/></button></div>{!company?<Gate text="Registra tu empresa o actividad empresarial antes de publicar." href="/empresa/onboarding"/>:company.status!=='verified'?<Gate text="Tu empresa debe estar verificada antes de publicar." href="/empresa"/>:!company.subscription?<Gate text="Elige y paga una membresía mensual para habilitar publicaciones." href="#planes" onClick={onClose}/>:<form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Título" value={form.title} set={v=>setForm({...form,title:v})}/><Field label="Categoría" value={form.category} set={v=>setForm({...form,category:v})}/><label className="sm:col-span-2"><span className="mb-2 block text-xs font-black">Descripción</span><textarea required minLength={10} rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="w-full rounded-xl border border-slate-200 p-3 text-sm"/></label><Field label="Precio MXN (opcional)" type="number" value={form.price} set={v=>setForm({...form,price:v})}/><Field label="URL de imagen HTTPS" value={form.image_url} set={v=>setForm({...form,image_url:v})}/><Field label="Teléfono" value={form.contact_phone} set={v=>setForm({...form,contact_phone:v})}/><Field label="WhatsApp" value={form.contact_whatsapp} set={v=>setForm({...form,contact_whatsapp:v})}/><button disabled={loading||!canPublish} className="min-h-12 rounded-xl bg-[#0f766e] text-sm font-black text-white sm:col-span-2">{loading?'Publicando…':'Publicar producto'}</button></form>}</div></div>
}
function Field({label,value,set,type='text'}){return <label><span className="mb-2 block text-xs font-black">{label}</span><input required={label==='Título'} type={type} value={value} onChange={e=>set(e.target.value)} className="h-12 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>}
function Gate({text,href,onClick}){return <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-6 text-center"><ShieldCheck className="mx-auto text-amber-700"/><p className="mt-3 text-sm font-bold text-slate-700">{text}</p><Link onClick={onClick} to={href} className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#062f33] px-5 text-xs font-black text-white">Continuar</Link></div>}
