import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, MapPinned, Plus, Route, ShieldAlert } from 'lucide-react'
import toast from 'react-hot-toast'
import OperationalWorkspace, { EmptyOperational, statusTone } from '../components/operations/OperationalWorkspace.jsx'
import { useOperationalContext } from '../hooks/useOperationalContext.js'
import { operationsApi } from '../lib/operationsApi.js'

const initial = { name:'', origin:'Manzanillo, Colima', destination:'', vehicle_type:'Tractocamión', vehicle_configuration:'sencillo', axle_count:5, trailer_count:1, gross_weight_kg:'', cargo_type:'Carga general', hazardous_material:false, oversized:false, sict_permit_expires_at:'', full_authorization_expires_at:'', connectivity_authorization_expires_at:'', road_name:'', road_class:'ET', start_km:'', end_km:'' }
const initialRule = { road_class:'ET', allowed_configuration:'sencillo', max_gross_weight_kg:'', requires_sict_permit:false, requires_full_authorization:false, requires_connectivity:false, source_name:'Captura empresarial', source_class:'manual' }

export default function SmartRoutes() {
  const context = useOperationalContext(), [routes,setRoutes] = useState([]), [catalogs,setCatalogs] = useState({rules:[],stops:[],risks:[]}), [form,setForm] = useState(initial), [rule,setRule] = useState(initialRule), [busy,setBusy] = useState(false)
  const load = () => context.companyId && Promise.all([operationsApi.routes(context.companyId),operationsApi.routeCatalogs(context.companyId)]).then(([result,catalog])=>{setRoutes(result.data);setCatalogs(catalog)}).catch((error)=>toast.error(error.message))
  useEffect(() => { load() },[context.companyId])
  const change = (key,value) => setForm((current)=>({...current,[key]:value}))
  const submit = async (event) => { event.preventDefault(); setBusy(true); try { const plan = await operationsApi.createRoute(context.companyId,{...form,segments:[{road_name:form.road_name,road_class:form.road_class,start_km:form.start_km,end_km:form.end_km}]}); const result = await operationsApi.evaluateRoute(context.companyId,plan.id); toast[result.evaluation.status==='blocked'?'error':'success'](result.evaluation.status==='blocked'?'La asignación fue bloqueada':'Ruta evaluada con la información disponible'); setForm(initial); load() } catch(error){toast.error(error.message)} finally{setBusy(false)} }
  const submitRule = async (event) => { event.preventDefault(); setBusy(true); try { await operationsApi.createLegalRule(context.companyId,{...rule,allowed_configurations:[rule.allowed_configuration]}); setRule(initialRule); toast.success('Regla legal registrada'); load() } catch(error){toast.error(error.message)} finally{setBusy(false)} }
  return <OperationalWorkspace title="Centro de Rutas Inteligentes y Seguridad" eyebrow="Planeación y cumplimiento" description="Evalúa cada segmento contra configuración, peso, dimensiones, permisos y reglas registradas. Información insuficiente nunca equivale a autorización." {...context}>
    {!context.companyId ? <EmptyOperational title={context.loading?'Cargando empresas':'Sin empresa operativa'} text={context.error || 'Registra o selecciona una empresa para crear planes de ruta.'}/> : <div className="grid gap-6 xl:grid-cols-[420px_1fr]">
      <form onSubmit={submit} className="self-start rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><MapPinned size={18} className="text-teal-700"/><h2 className="font-black">Nueva evaluación</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">La ruta se bloquea ante incompatibilidad, permisos faltantes o reglas críticas incompletas.</p>
        <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-1">{[['name','Nombre del viaje'],['origin','Origen'],['destination','Destino'],['road_name','Carretera o tramo']].map(([key,label])=><Field key={key} label={label}><input required value={form[key]} onChange={(e)=>change(key,e.target.value)} className="input-op"/></Field>)}
          <div className="grid grid-cols-3 gap-2"><Field label="Clase"><select value={form.road_class} onChange={(e)=>change('road_class',e.target.value)} className="input-op">{['ET','A','B','C','D','STATE','MUNICIPAL','PORT','CUSTOMS','PRIVATE'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Km inicial"><input type="number" value={form.start_km} onChange={(e)=>change('start_km',e.target.value)} className="input-op"/></Field><Field label="Km final"><input type="number" value={form.end_km} onChange={(e)=>change('end_km',e.target.value)} className="input-op"/></Field></div>
          <div className="grid grid-cols-2 gap-2"><Field label="Configuración"><select value={form.vehicle_configuration} onChange={(e)=>change('vehicle_configuration',e.target.value)} className="input-op"><option value="sencillo">Sencillo</option><option value="full">Full</option><option value="torton">Torton</option><option value="rabon">Rabón</option></select></Field><Field label="Peso bruto kg"><input required type="number" min="1" value={form.gross_weight_kg} onChange={(e)=>change('gross_weight_kg',e.target.value)} className="input-op"/></Field></div>
          <Field label="Tipo de mercancía"><input value={form.cargo_type} onChange={(e)=>change('cargo_type',e.target.value)} className="input-op"/></Field>
          <div className="grid grid-cols-2 gap-2"><Field label="Vigencia permiso SICT"><input type="date" value={form.sict_permit_expires_at} onChange={(e)=>change('sict_permit_expires_at',e.target.value)} className="input-op"/></Field><Field label="Vigencia autorización full"><input type="date" value={form.full_authorization_expires_at} onChange={(e)=>change('full_authorization_expires_at',e.target.value)} className="input-op"/></Field></div>
          <label className="flex items-center gap-2 text-xs font-bold text-slate-700"><input type="checkbox" checked={form.hazardous_material} onChange={(e)=>change('hazardous_material',e.target.checked)}/> Material peligroso</label>
        </div><button disabled={busy} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#0d5b55] text-xs font-black text-white disabled:opacity-50"><Plus size={15}/>{busy?'Evaluando…':'Crear y evaluar ruta'}</button>
      </form>
      <section><div className="grid gap-3 sm:grid-cols-3"><Metric icon={Route} value={routes.length} label="Planes registrados"/><Metric icon={ShieldAlert} value={routes.filter(x=>x.status==='blocked').length} label="Asignaciones bloqueadas"/><Metric icon={CheckCircle2} value={routes.filter(x=>x.status==='approved').length} label="Evaluaciones aprobadas"/></div>
        <form onSubmit={submitRule} className="mt-5 rounded-2xl border border-amber-200 bg-amber-50/60 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-black">Catálogo legal de la empresa</h2><p className="mt-1 text-xs text-slate-600">{catalogs.rules.length} reglas registradas. Una captura manual no se presenta como criterio oficial.</p></div><span className="rounded-full bg-white px-3 py-1 text-[10px] font-black text-amber-800">Fuente obligatoria</span></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Field label="Clase"><select value={rule.road_class} onChange={e=>setRule({...rule,road_class:e.target.value})} className="input-op">{['ET','A','B','C','D','STATE','MUNICIPAL','PORT','CUSTOMS','PRIVATE'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Configuración permitida"><select value={rule.allowed_configuration} onChange={e=>setRule({...rule,allowed_configuration:e.target.value})} className="input-op"><option value="sencillo">Sencillo</option><option value="full">Full</option><option value="torton">Torton</option><option value="rabon">Rabón</option></select></Field><Field label="Peso máximo kg"><input required type="number" min="1" value={rule.max_gross_weight_kg} onChange={e=>setRule({...rule,max_gross_weight_kg:e.target.value})} className="input-op"/></Field><Field label="Fuente"><input required value={rule.source_name} onChange={e=>setRule({...rule,source_name:e.target.value})} className="input-op"/></Field></div><div className="mt-3 flex flex-wrap items-center gap-4"><label className="text-xs font-bold"><input className="mr-2" type="checkbox" checked={rule.requires_sict_permit} onChange={e=>setRule({...rule,requires_sict_permit:e.target.checked})}/>Exige permiso SICT</label><label className="text-xs font-bold"><input className="mr-2" type="checkbox" checked={rule.requires_full_authorization} onChange={e=>setRule({...rule,requires_full_authorization:e.target.checked})}/>Exige autorización full</label><button disabled={busy} className="ml-auto rounded-lg bg-amber-900 px-4 py-2 text-xs font-black text-white">Guardar regla</button></div></form>
        <div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-black">Planes recientes</h2><p className="mt-1 text-xs text-slate-500">Resultados basados exclusivamente en reglas cargadas para la empresa.</p></div>{routes.length ? <div className="divide-y divide-slate-100">{routes.map((route)=><article key={route.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{route.name}</h3><span className={`rounded-full border px-2 py-1 text-[9px] font-black uppercase ${statusTone(route.status)}`}>{route.status}</span></div><p className="mt-2 text-sm text-slate-600">{route.origin} → {route.destination}</p><p className="mt-1 text-xs text-slate-400">{route.vehicle_configuration} · Actualizado {new Date(route.updated_at).toLocaleString('es-MX')}</p>{route.blocking_reasons?.length>0&&<div className="mt-3 rounded-lg bg-red-50 p-3 text-xs leading-5 text-red-800"><AlertTriangle size={14} className="mb-1"/>{route.blocking_reasons.join(' · ')}</div>}</div><button onClick={async()=>{setBusy(true);try{await operationsApi.evaluateRoute(context.companyId,route.id);load()}catch(e){toast.error(e.message)}finally{setBusy(false)}}} className="h-9 rounded-lg border border-slate-200 px-3 text-xs font-black">Reevaluar</button></article>)}</div>:<EmptyOperational title="Todavía no hay rutas" text="Crea la primera evaluación. Sin reglas legales cargadas, el resultado será información insuficiente y la asignación quedará bloqueada."/>}</div>
      </section>
    </div>}
    <p className="mt-6 text-xs leading-5 text-slate-500">Faro Portuario ayuda a prevenir errores, pero no sustituye a la autoridad, al permisionario ni a la revisión jurídica especializada.</p>
  </OperationalWorkspace>
}
function Field({label,children}){return <label className="block text-[10px] font-black uppercase tracking-[.12em] text-slate-500">{label}{children}</label>}
function Metric({icon:Icon,value,label}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><Icon size={17} className="text-teal-700"/><p className="mt-3 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>}
