import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
export const RESOURCE_ROOT = path.resolve(__dirname, '../../assets/resources')

const common = {
  access: 'registered',
  price: 0,
  currency: 'MXN',
  version: '1.0',
  reviewedAt: '2026-07-14',
}

export const RESOURCE_CATALOG = [
  {
    ...common,
    id: 'checklist-unidad-nom068',
    library: 'templates',
    title: 'Checklist de unidad — NOM-068',
    description: 'Libro editable para revisar la unidad, registrar hallazgos, responsables y una decisión de liberación.',
    format: 'XLSX',
    file: 'templates/faro_checklist_unidad_nom068.xlsx',
    downloadName: 'Faro_Portuario_Checklist_Unidad_NOM068.xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'Transporte',
    audiences: ['Transportistas', 'Operadores', 'Mantenimiento'],
    highlights: ['3 hojas editables', 'Resultado automático', 'Datos de empresa'],
  },
  {
    ...common,
    id: 'bitacora-conduccion-nom087',
    library: 'templates',
    title: 'Bitácora de conducción y pausas',
    description: 'Control de jornadas, horas de conducción, pausas y excepciones con resumen calculado.',
    format: 'XLSX',
    file: 'templates/faro_bitacora_conduccion_nom087.xlsx',
    downloadName: 'Faro_Portuario_Bitacora_Conduccion_NOM087.xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'Transporte',
    audiences: ['Operadores', 'Transportistas', 'Tráfico'],
    highlights: ['100 registros', 'Cálculo de horas', 'Resumen de control'],
  },
  {
    ...common,
    id: 'control-mantenimiento-flota',
    library: 'templates',
    title: 'Control de mantenimiento de flota',
    description: 'Catálogo de unidades, órdenes de servicio, costos con IVA y seguimiento de liberación.',
    format: 'XLSX',
    file: 'templates/faro_control_mantenimiento_flota.xlsx',
    downloadName: 'Faro_Portuario_Control_Mantenimiento_Flota.xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'Mantenimiento',
    audiences: ['Transportistas', 'Mantenimiento', 'Administración'],
    highlights: ['4 hojas editables', 'Costos automáticos', 'Control por unidad'],
  },
  {
    ...common,
    id: 'control-previo-carta-porte',
    library: 'templates',
    title: 'Control previo Carta Porte',
    description: 'Matriz para reunir ubicaciones, mercancías, unidad, operador, seguro y validaciones antes del sistema autorizado.',
    format: 'XLSX',
    file: 'templates/faro_control_previo_carta_porte.xlsx',
    downloadName: 'Faro_Portuario_Control_Previo_Carta_Porte.xlsx',
    mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'Comercio exterior',
    audiences: ['Transportistas', 'Freight forwarders', 'Facturación'],
    highlights: ['4 hojas editables', 'Mercancías por partida', 'Validación interna'],
  },
  {
    ...common,
    id: 'reporte-incidente-operativo',
    library: 'templates',
    title: 'Reporte de incidente operativo',
    description: 'Formato editable para clasificar, describir, contener, investigar y dar seguimiento a un incidente.',
    format: 'DOCX',
    file: 'templates/faro_reporte_incidente_operativo.docx',
    downloadName: 'Faro_Portuario_Reporte_Incidente_Operativo.docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    category: 'Seguridad',
    audiences: ['Transportistas', 'Almacenes', 'Maniobristas'],
    highlights: ['Word editable', 'Análisis de causa', 'Control de acciones'],
  },
  {
    ...common,
    id: 'acta-entrega-recepcion',
    library: 'templates',
    title: 'Acta de entrega y recepción',
    description: 'Formato para registrar mercancía, sellos, condición, reservas, evidencia y firmas de las partes.',
    format: 'DOCX',
    file: 'templates/faro_acta_entrega_recepcion_mercancia.docx',
    downloadName: 'Faro_Portuario_Acta_Entrega_Recepcion.docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    category: 'Operación',
    audiences: ['Almacenes', 'Transportistas', 'Freight forwarders'],
    highlights: ['Word editable', 'Control de sellos', 'Reservas y firmas'],
  },
  {
    ...common,
    id: 'plan-accion-correctiva',
    library: 'templates',
    title: 'Plan de acción correctiva',
    description: 'Documento editable para definir problemas, confirmar causa raíz y verificar la eficacia de las acciones.',
    format: 'DOCX',
    file: 'templates/faro_plan_accion_correctiva.docx',
    downloadName: 'Faro_Portuario_Plan_Accion_Correctiva.docx',
    mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    category: 'Calidad',
    audiences: ['Todas las empresas', 'Calidad', 'Seguridad'],
    highlights: ['Word editable', 'Causa raíz', 'Eficacia y cierre'],
  },
  {
    ...common,
    id: 'curso-manejo-seguro-fatiga',
    library: 'training',
    title: 'Buenas prácticas de manejo seguro',
    description: 'Prevención de fatiga, pausas, conducción defensiva y respuesta de tráfico ante ventanas imposibles.',
    format: 'PDF',
    file: 'training/faro_buenas_practicas_manejo_seguro.pdf',
    downloadName: 'Faro_Portuario_Buenas_Practicas_Manejo_Seguro.pdf',
    mime: 'application/pdf',
    category: 'Transportistas',
    audiences: ['Operadores', 'Transportistas', 'Tráfico'],
    duration: '35 min',
    reference: 'NOM-087-SCT-2-2017',
  },
  {
    ...common,
    id: 'curso-inspeccion-preoperativa',
    library: 'training',
    title: 'Inspección preoperativa de unidades',
    description: 'Revisión visual ordenada, clasificación de hallazgos y evidencia antes de liberar una unidad.',
    format: 'PDF',
    file: 'training/faro_inspeccion_preoperativa_nom068.pdf',
    downloadName: 'Faro_Portuario_Inspeccion_Preoperativa_NOM068.pdf',
    mime: 'application/pdf',
    category: 'Transportistas',
    audiences: ['Operadores', 'Mantenimiento', 'Seguridad'],
    duration: '40 min',
    reference: 'NOM-068-SCT-2-2014',
  },
  {
    ...common,
    id: 'curso-peso-dimensiones-carga',
    library: 'training',
    title: 'Peso, dimensiones y sujeción de carga',
    description: 'Configuración, distribución por ejes, ruta, sujeción y evidencia antes de una ruta federal.',
    format: 'PDF',
    file: 'training/faro_peso_dimensiones_sujecion_carga.pdf',
    downloadName: 'Faro_Portuario_Peso_Dimensiones_Sujecion_Carga.pdf',
    mime: 'application/pdf',
    category: 'Transportistas',
    audiences: ['Transportistas', 'Freight forwarders', 'Almacenes'],
    duration: '35 min',
    reference: 'NOM-012-SCT-2-2017',
  },
  {
    ...common,
    id: 'curso-mercancias-peligrosas',
    library: 'training',
    title: 'Mercancías peligrosas',
    description: 'Identificación documental y visual, compatibilidad y respuesta inicial sin improvisación.',
    format: 'PDF',
    file: 'training/faro_mercancias_peligrosas_identificacion.pdf',
    downloadName: 'Faro_Portuario_Mercancias_Peligrosas.pdf',
    mime: 'application/pdf',
    category: 'Seguridad',
    audiences: ['Transportistas', 'Almacenes', 'Maniobristas'],
    duration: '45 min',
    reference: 'NOM-002/2023 y NOM-004/2008',
  },
  {
    ...common,
    id: 'curso-almacenes-maniobristas',
    library: 'training',
    title: 'Manejo y almacenamiento seguro',
    description: 'Planificación de maniobras, interacción peatón-equipo, estiba y control de cierre.',
    format: 'PDF',
    file: 'training/faro_manejo_almacenamiento_seguro_nom006.pdf',
    downloadName: 'Faro_Portuario_Manejo_Almacenamiento_NOM006.pdf',
    mime: 'application/pdf',
    category: 'Almacenes',
    audiences: ['Almacenes', 'Maniobristas', 'Seguridad'],
    duration: '40 min',
    reference: 'NOM-006-STPS-2014',
  },
  {
    ...common,
    id: 'curso-carta-porte',
    library: 'training',
    title: 'Carta Porte: control operativo previo',
    description: 'Recolección y conciliación de datos antes de enviarlos al sistema autorizado de facturación.',
    format: 'PDF',
    file: 'training/faro_carta_porte_control_operativo.pdf',
    downloadName: 'Faro_Portuario_Carta_Porte_Control_Operativo.pdf',
    mime: 'application/pdf',
    category: 'Comercio exterior',
    audiences: ['Transportistas', 'Facturación', 'Freight forwarders'],
    duration: '45 min',
    reference: 'Portal oficial SAT',
  },
  {
    ...common,
    id: 'curso-vucem-expediente',
    library: 'training',
    title: 'VUCEM y expediente digital',
    description: 'Control de documentos, versiones, transmisiones, acuses y rechazos en comercio exterior.',
    format: 'PDF',
    file: 'training/faro_vucem_expediente_digital.pdf',
    downloadName: 'Faro_Portuario_VUCEM_Expediente_Digital.pdf',
    mime: 'application/pdf',
    category: 'Comercio exterior',
    audiences: ['Agentes aduanales', 'Freight forwarders', 'Importadores'],
    duration: '40 min',
    reference: 'VUCEM y ANAM',
  },
  {
    ...common,
    id: 'curso-coordinacion-aduanal',
    library: 'training',
    title: 'Coordinación aduanal para agentes y forwarders',
    description: 'Instrucciones, pedimento, anexos, liberación y cierre de expedientes con trazabilidad.',
    format: 'PDF',
    file: 'training/faro_coordinacion_aduanal_forwarders_2026.pdf',
    downloadName: 'Faro_Portuario_Coordinacion_Aduanal_2026.pdf',
    mime: 'application/pdf',
    category: 'Agentes y forwarders',
    audiences: ['Agentes aduanales', 'Freight forwarders', 'Tráfico'],
    duration: '50 min',
    reference: 'RGCE 2026, Anexo 22 y ANAM',
  },
]

export function publicResource(resource) {
  const { file, mime, ...safe } = resource
  return safe
}

export function findResource(id) {
  return RESOURCE_CATALOG.find((resource) => resource.id === id)
}

export function absoluteResourcePath(resource) {
  const fullPath = path.resolve(RESOURCE_ROOT, resource.file)
  if (!fullPath.startsWith(`${RESOURCE_ROOT}${path.sep}`)) throw new Error('Ruta de recurso inválida')
  return fullPath
}
